"""AGA Configuration — .aga.yaml model and loader.

Search chain (first wins):
  1. ./.aga.yaml  (project-level, in CWD or nearest parent with .aga.yaml / .git)
  2. ~/.aga.yaml   (user-level)
  3. Built-in defaults

Example .aga.yaml:

    rules_source: "https://raw.githubusercontent.com/aaa-mvc/aga/main/community/rules"
    gate_threshold: "high"
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# ── Default values ───────────────────────────────────────────────

DEFAULT_RULES_SOURCE = "https://raw.githubusercontent.com/aaa-mvc/aga/main/community/rules"
DEFAULT_GATE_THRESHOLD = "high"  # low | medium | high | critical

# ── Config Model ─────────────────────────────────────────────────


class Config(BaseModel):
    """AGA configuration loaded from .aga.yaml."""

    rules_source: str = Field(
        default=DEFAULT_RULES_SOURCE,
        description="Remote URL for community rule index.yaml",
    )
    gate_threshold: str = Field(
        default=DEFAULT_GATE_THRESHOLD,
        description="Risk level that blocks installation: low | medium | high | critical",
    )

    def gate_blocks(self, risk_level: str) -> bool:
        """Return True if *risk_level* should be blocked by the gate threshold.

        Threshold semantics:
          - "critical" → only CRITICAL is blocked
          - "high"     → HIGH + CRITICAL are blocked
          - "medium"   → MEDIUM + HIGH + CRITICAL are blocked
          - "low"      → everything is blocked (strictest)
        """
        levels = ("low", "medium", "high", "critical")
        try:
            threshold_idx = levels.index(self.gate_threshold)
            risk_idx = levels.index(risk_level.lower())
            return risk_idx >= threshold_idx
        except ValueError:
            # Unknown level → conservative: don't block
            return False


# ── ConfigLoader ──────────────────────────────────────────────────


class ConfigLoader:
    """Discover and load AGA configuration from disk.

    Usage:
        config = ConfigLoader.load()
        config = ConfigLoader.load(project_dir=Path.cwd())
    """

    CONFIG_FILENAME = ".aga.yaml"

    @classmethod
    def load(cls, project_dir: Path | None = None) -> Config:
        """Load Config from the first available source in the search chain.

        Args:
            project_dir: Directory to use as the project root.
                         If not given, defaults to CWD.

        Returns:
            Config instance (never None — defaults are always available).
        """
        project_dir = (project_dir or Path.cwd()).resolve()

        # 1. Project-level: ./.aga.yaml (nearest parent with .aga.yaml or .git)
        project_config = cls._find_project_config(project_dir)
        if project_config:
            logger.debug(f"Loaded config from {project_config}")
            return Config.model_validate(project_config)

        # 2. User-level: ~/.aga.yaml
        user_config = cls._read_yaml(Path.home() / cls.CONFIG_FILENAME)
        if user_config:
            logger.debug(f"Loaded config from ~/ {cls.CONFIG_FILENAME}")
            return Config.model_validate(user_config)

        # 3. Defaults
        logger.debug("No config file found — using defaults")
        return Config()

    @classmethod
    def save(cls, config: Config, path: Path) -> None:
        """Write a Config to disk as YAML.

        Args:
            config: The Config object to persist.
            path: Absolute file path to write to.
        """
        data = {
            "rules_source": config.rules_source,
            "gate_threshold": config.gate_threshold,
        }
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# AGA Configuration\n"
            "# Generated by `aga init`.\n"
            "#\n"
            f"rules_source: \"{data['rules_source']}\"\n"
            f"gate_threshold: \"{data['gate_threshold']}\"\n",
            encoding="utf-8",
        )

    @staticmethod
    def find_project_root(start_dir: Path) -> Path | None:
        """Walk upward from *start_dir* to find a project root.

        A project root is a directory containing .aga.yaml or .git/.
        Returns the directory path, or None if none found before filesystem root.
        """
        current = start_dir.resolve()
        root = current.anchor  # e.g. "C:\\" or "/"
        while current != Path(root) and current != Path(current.anchor):
            if (current / ConfigLoader.CONFIG_FILENAME).exists():
                return current
            if (current / ".git").exists():
                return current
            parent = current.parent
            if parent == current:
                break
            current = parent
        return None

    # ── Private helpers ──────────────────────────────────────────

    @classmethod
    def _find_project_config(cls, start_dir: Path) -> dict[str, Any] | None:
        """Search upward from start_dir for .aga.yaml."""
        current = start_dir
        root = current.anchor
        while True:
            data = cls._read_yaml(current / cls.CONFIG_FILENAME)
            if data is not None:
                return data
            parent = current.parent
            if parent == current or str(current) == root:
                break
            current = parent
        return None

    @staticmethod
    def _read_yaml(path: Path) -> dict[str, Any] | None:
        """Read a YAML file and return its contents as a dict, or None."""
        if not path.is_file():
            return None
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return data
            logger.warning(f"Config file {path} is not a mapping — ignoring")
            return None
        except Exception as exc:
            logger.warning(f"Failed to parse {path}: {exc}")
            return None


# ── Helpers for CLI ──────────────────────────────────────────────


def resolve_install_path(
    local: bool = False,
    global_: bool = False,
    project_dir: Path | None = None,
) -> Path:
    """Resolve the rule installation directory.

    Args:
        local: Use project-level .aga/rules/.
        global_: Use user-level ~/.aga/rules/.
        project_dir: Override project directory. Defaults to CWD.

    Returns:
        Absolute path to the rules directory.
    """
    if global_:
        return Path.home() / ".aga" / "rules"

    if local:
        proj = (project_dir or Path.cwd()).resolve()
        if ConfigLoader.find_project_root(proj) is None:
            # No project root found → create .aga/ in CWD
            pass
        return proj / ".aga" / "rules"

    # Default: auto-detect — project if inside one, else global
    proj = (project_dir or Path.cwd()).resolve()
    if ConfigLoader.find_project_root(proj):
        return proj / ".aga" / "rules"
    return Path.home() / ".aga" / "rules"
